# Using Numpy Random Module

Numpy allows you to generate all kinds of random variables and also it is very fast.

In [1]:
import numpy as np

In [2]:
np.random.random()

0.5432685610778782

In [3]:
np.random.random(5)

array([0.31355646, 0.86394176, 0.70477849, 0.59958365, 0.28566427])

To generate a 2-D random array

In [4]:
np.random.random((5,3))

array([[0.05268344, 0.08526546, 0.86137056],
       [0.37181635, 0.17072196, 0.68075602],
       [0.59663903, 0.37838794, 0.79412683],
       [0.99616846, 0.36822827, 0.02178039],
       [0.78608003, 0.55151847, 0.95208063]])

Generating a random normal distribution requires two parameters mean and standard deviation as inputs.Setting mean as 0 and standard deviation as 1 gives us normal distribution.To generate random numbers from standard normal distribution we use the following:

In [7]:
np.random.normal(0,1)

-1.783494781595008

To generate an array of given length we provide that as our 3 input parameter.
The dimensions of array are added as tuple.

In [9]:
np.random.normal(0,1,(2,2))

array([[ 2.31497396, -0.51183031],
       [-0.06664473,  0.4646505 ]])